# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Seafile\Code\Senior1\HCI2\spirit_gen_demo\ui\borndialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BornDialog(object):
    def setupUi(self, BornDialog):
        BornDialog.setObjectName("BornDialog")
        BornDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        BornDialog.resize(360, 380)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        BornDialog.setWindowIcon(icon)
        BornDialog.setStyleSheet("#BornDialog{background-color: rgb(255, 255, 255);}")
        self.SpiritImgLarge = QtWidgets.QLabel(BornDialog)
        self.SpiritImgLarge.setGeometry(QtCore.QRect(60, 20, 240, 240))
        self.SpiritImgLarge.setStyleSheet("")
        self.SpiritImgLarge.setObjectName("SpiritImgLarge")
        self.BornHint = QtWidgets.QLabel(BornDialog)
        self.BornHint.setGeometry(QtCore.QRect(10, 280, 340, 40))
        self.BornHint.setPixmap(QtGui.QPixmap(":/HatchingHouse/Born/new.png"))
        self.BornHint.setObjectName("BornHint")
        self.YesButton = QtWidgets.QPushButton(BornDialog)
        self.YesButton.setGeometry(QtCore.QRect(135, 330, 90, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YesButton.sizePolicy().hasHeightForWidth())
        self.YesButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/SpiritUniverse/yes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.YesButton.setIcon(icon1)
        self.YesButton.setIconSize(QtCore.QSize(90, 30))
        self.YesButton.setObjectName("YesButton")

        self.retranslateUi(BornDialog)
        QtCore.QMetaObject.connectSlotsByName(BornDialog)

    def retranslateUi(self, BornDialog):
        _translate = QtCore.QCoreApplication.translate
        BornDialog.setWindowTitle(_translate("BornDialog", "Congratulations!"))
import resources_rc
