# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Seafile\Code\Senior1\HCI2\spirit_gen_demo\ui\SpiritThumb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpiritThumb(object):
    def setupUi(self, SpiritThumb):
        SpiritThumb.setObjectName("SpiritThumb")
        SpiritThumb.resize(160, 200)
        self.SpiritId = QtWidgets.QLabel(SpiritThumb)
        self.SpiritId.setGeometry(QtCore.QRect(20, 160, 120, 20))
        self.SpiritId.setStyleSheet("font: 57 10pt \"Press Start 2P\";")
        self.SpiritId.setAlignment(QtCore.Qt.AlignCenter)
        self.SpiritId.setObjectName("SpiritId")
        self.SpiritImg = QtWidgets.QLabel(SpiritThumb)
        self.SpiritImg.setGeometry(QtCore.QRect(20, 20, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpiritImg.sizePolicy().hasHeightForWidth())
        self.SpiritImg.setSizePolicy(sizePolicy)
        self.SpiritImg.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.SpiritImg.setObjectName("SpiritImg")

        self.retranslateUi(SpiritThumb)
        QtCore.QMetaObject.connectSlotsByName(SpiritThumb)

    def retranslateUi(self, SpiritThumb):
        _translate = QtCore.QCoreApplication.translate
        SpiritThumb.setWindowTitle(_translate("SpiritThumb", "Form"))
        self.SpiritId.setText(_translate("SpiritThumb", "No.00000"))
