# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Seafile\Code\Senior1\HCI2\spirit_gen_demo\ui\spirithouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpiritHouse(object):
    def setupUi(self, SpiritHouse):
        SpiritHouse.setObjectName("SpiritHouse")
        SpiritHouse.setWindowModality(QtCore.Qt.NonModal)
        SpiritHouse.resize(960, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SpiritHouse.sizePolicy().hasHeightForWidth())
        SpiritHouse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Press Start 2P")
        SpiritHouse.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Seafile\\Code\\Senior1\\HCI2\\spirit_gen_demo\\ui\\../assets/UI/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("D:\\Seafile\\Code\\Senior1\\HCI2\\spirit_gen_demo\\ui\\../assets/UI/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        SpiritHouse.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SpiritHouse)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 960, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Background.sizePolicy().hasHeightForWidth())
        self.Background.setSizePolicy(sizePolicy)
        self.Background.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Background.setPixmap(QtGui.QPixmap(":/background.png"))
        self.Background.setObjectName("Background")
        self.TopBar = QtWidgets.QLabel(self.centralwidget)
        self.TopBar.setGeometry(QtCore.QRect(0, 0, 960, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopBar.sizePolicy().hasHeightForWidth())
        self.TopBar.setSizePolicy(sizePolicy)
        self.TopBar.setPixmap(QtGui.QPixmap(":/topBar.png"))
        self.TopBar.setObjectName("TopBar")
        self.GoHatchingButton = QtWidgets.QPushButton(self.centralwidget)
        self.GoHatchingButton.setGeometry(QtCore.QRect(269, 640, 422, 62))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoHatchingButton.sizePolicy().hasHeightForWidth())
        self.GoHatchingButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/SpiritHouse/go-hatching-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.GoHatchingButton.setIcon(icon1)
        self.GoHatchingButton.setIconSize(QtCore.QSize(484, 71))
        self.GoHatchingButton.setObjectName("GoHatchingButton")
        self.SpiritUniverseButton = QtWidgets.QPushButton(self.centralwidget)
        self.SpiritUniverseButton.setGeometry(QtCore.QRect(239, 40, 482, 72))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpiritUniverseButton.sizePolicy().hasHeightForWidth())
        self.SpiritUniverseButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/SpiritHouse/spirit-universe-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.SpiritUniverseButton.setIcon(icon2)
        self.SpiritUniverseButton.setIconSize(QtCore.QSize(484, 71))
        self.SpiritUniverseButton.setObjectName("SpiritUniverseButton")
        self.SpiritsArea = QtWidgets.QScrollArea(self.centralwidget)
        self.SpiritsArea.setGeometry(QtCore.QRect(30, 140, 902, 482))
        self.SpiritsArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.SpiritsArea.setWidgetResizable(True)
        self.SpiritsArea.setObjectName("SpiritsArea")
        self.SpiritsHouseContent = QtWidgets.QWidget()
        self.SpiritsHouseContent.setGeometry(QtCore.QRect(0, 0, 900, 480))
        self.SpiritsHouseContent.setObjectName("SpiritsHouseContent")
        self.SpiritsArea.setWidget(self.SpiritsHouseContent)
        SpiritHouse.setCentralWidget(self.centralwidget)

        self.retranslateUi(SpiritHouse)
        QtCore.QMetaObject.connectSlotsByName(SpiritHouse)

    def retranslateUi(self, SpiritHouse):
        _translate = QtCore.QCoreApplication.translate
        SpiritHouse.setWindowTitle(_translate("SpiritHouse", "Pixel Spirit"))
import resources_rc
