# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Seafile\Code\Senior1\HCI2\spirit_gen_demo\ui\universedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UniverseDialog(object):
    def setupUi(self, UniverseDialog):
        UniverseDialog.setObjectName("UniverseDialog")
        UniverseDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        UniverseDialog.resize(320, 440)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        UniverseDialog.setWindowIcon(icon)
        UniverseDialog.setStyleSheet("#UniverseDialog {background-color: rgb(255, 255, 255);}")
        self.UniverseHint = QtWidgets.QLabel(UniverseDialog)
        self.UniverseHint.setGeometry(QtCore.QRect(10, 280, 300, 90))
        self.UniverseHint.setPixmap(QtGui.QPixmap(":/SpiritUniverse/Hint.png"))
        self.UniverseHint.setObjectName("UniverseHint")
        self.SpiritImgLarge = QtWidgets.QLabel(UniverseDialog)
        self.SpiritImgLarge.setGeometry(QtCore.QRect(40, 20, 240, 240))
        self.SpiritImgLarge.setObjectName("SpiritImgLarge")
        self.Greeting = QtWidgets.QLabel(UniverseDialog)
        self.Greeting.setGeometry(QtCore.QRect(150, 10, 160, 80))
        self.Greeting.setPixmap(QtGui.QPixmap(":/SpiritUniverse/Bubble.png"))
        self.Greeting.setObjectName("Greeting")
        self.UniverseYesButton = QtWidgets.QPushButton(UniverseDialog)
        self.UniverseYesButton.setGeometry(QtCore.QRect(50, 400, 90, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UniverseYesButton.sizePolicy().hasHeightForWidth())
        self.UniverseYesButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/SpiritUniverse/yes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UniverseYesButton.setIcon(icon1)
        self.UniverseYesButton.setIconSize(QtCore.QSize(90, 30))
        self.UniverseYesButton.setObjectName("UniverseYesButton")
        self.UniverseNoButton = QtWidgets.QPushButton(UniverseDialog)
        self.UniverseNoButton.setGeometry(QtCore.QRect(180, 400, 90, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UniverseNoButton.sizePolicy().hasHeightForWidth())
        self.UniverseNoButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/SpiritUniverse/no.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UniverseNoButton.setIcon(icon2)
        self.UniverseNoButton.setIconSize(QtCore.QSize(90, 30))
        self.UniverseNoButton.setObjectName("UniverseNoButton")

        self.retranslateUi(UniverseDialog)
        QtCore.QMetaObject.connectSlotsByName(UniverseDialog)

    def retranslateUi(self, UniverseDialog):
        _translate = QtCore.QCoreApplication.translate
        UniverseDialog.setWindowTitle(_translate("UniverseDialog", "Meet A Spirit"))
import resources_rc
